### ISSUE TITLE
New version of Velocidrone with disconecting issue with CRSFJoystick

### ISSUE THREAD

**Issue by eduardorcosta** [mikeneiderhauser/CRSFJoystick#25] opened 2024-02-01 01:14 UTC
Hi, sorry to bother but, I donwload the lastest version of velocidrone, that I'm runing with Waveshare RP2040 and ELRS, but it now has some strange behaviours.
Just to metion the previous version of velocidrone works like a charm with it.
The new one, I think that reads the reset button in my case Aux 6, really does not think it matters as I change it sometimes. 
In the midle of the game, it just stops and seens everything is reset.
I open a bug in velocidrone also to be shure.
Just open here to, if anyone is having the same issue.

If you want some information, log anything let me know please.
Thank you for such a great project!

**Comment by sk8board** [comment] 2024-02-01 02:34
I had a similar problem with the update of Velocidrone. I had to reset my controller settings in Velocidrone. When I setup my controller settings again, I found the UI would not function correctly. 

I had to select the "Legacy" button on the UI to use the old controller setup UI, then I was able to get the controller settings working as I wanted. I have not had any problems since deleting my controller settings then use the legacy UI to setup my controller settings again.

**Comment by eduardorcosta** [comment] 2024-02-01 02:52
> to

I also reset the settings, the support of velocidrone recommended it.
But any of the versions of the controller setup works ok.
Is in the gameplay that the problem arises, as it seems to reset in the middle of flight
Everything stops, if I'm racing, the race stops, and the first gate is light.

**Comment by sk8board** [comment] 2024-02-01 13:19
If your controller has a USB connection, then directly connect the controller to the PC to see if the problem is still present.

If the problem is still present when directly connected using USB from the controller to the PC, then this would show their is an incompatibility between the controller and the PC or Velocidrone.

If the problem is no longer present when directly connected using USB from the controller to the PC, then this would indicate the problem is with either the receiver, CRSFJoystick software, or possibly the Waveshare RP2040-Zero.

**Comment by eduardorcosta** [comment] 2024-02-01 13:28
Yes, I tried the USB connection and it worked flawlessly.
You mention the interface, I have been trying to identify the problem, so I change buttons, remove all.
The problem is the start race button. If I mapped it as a button on the legacy interface, it has the problem, but if I mapped it as an Axis, the behaviour does not appear.
But as I said to batcave support, it did not appear in the older version of velocidrone, just this release.

**Comment by sk8board** [comment] 2024-02-01 17:32
> The problem is the start race button. If I mapped it as a button on the legacy interface, it has the problem, but if I mapped it as an Axis, the behaviour does not appear.

It seems you are stating the problem is resolved if you map to an Axis rather than a Button. If so, why don't you just use the Axis?

**Comment by eduardorcosta** [comment] 2024-02-01 19:10
Yes I changed, and it resolved. But why this only show in this version I don't know.

**Comment by sk8board** [comment] 2024-02-01 19:15
The update to Velocidrone definitely broke the Controller setup UI. I suspect there is more to this break than just the UI. Eventually the Bat Cave will get is fixed. Until then, you have a workaround that is easy to use.

**Comment by eduardorcosta** [comment] 2024-02-01 19:19
Yes!

**Comment by mikeneiderhauser** [comment] 2024-11-01 23:21
Seems like this is resolved and is a Velocidrone issue. Closing

**Closed by mikeneiderhauser** 2024-11-01 23:21 UTC
